= История изменений

== [0.1.2] - в новом релизе

* Исправлена ошибка в DER-кодировщике. Размер координат точки EC определяется модулем поля p, а не порядком группы n. Из-за этого был неверный вывод при кодировании. Устранена двойная OCTET STRING обёртка закрытого ключа.

== [0.1.1] - 2026-04-30

*  В JCA провайдер добавлен алиас `Kuznyechik/MGM/NoPadding` для режима `Kuznyechik-MGM`. Это название более идиоматично для JCA. Добавлен соответствующий тест `Kuznyechik/MGM/NoPadding`.
* В документацию README внесены мелкие исправления и уточнения формулировок.
* Внесены дополнительные сведения в pom.xml о разработчике, лицензии и репозитории.
* Добавлено подписывание jar-файлов моим публичным ключом. В файл `KEYS` добавлен мой публичный ключ.
* Добавлены новые методы + тесты к ним + документация:
** *signHash(byte[] hash,PrivateKeyParameters priv)* — подписывает готовый хэш. Внутри использует ECDSASigner.generateSignature() напрямую, минуя DigestSigner. RFC 6979 детерминизм сохраняется.
** *verifyHash(byte[] hash, byte[] signature, PublicKeyParameters pub)* — проверяет подпись готового хэша через ECDSASigner.verifySignature().
* добавлено обнуление данных dBytes в ECDSASigner.
* добавлен вспомогательный класс *SignatureCodec* для вызова из разных мест, чтобы избежать дублирования.
* проведены тесты на кросс-валидацию повторно.

== [0.1.0] - 2026-04-28

Начальный выпуск.


